image: hashicorp/terraform:latest

stages:
  - plan
  - apply
  - destroy

before_script:
  - terraform --version
  - terraform init

plan:
  stage: plan
  script:
    - terraform plan -out="planfile"
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -auto-approve planfile
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
